=== harikrishnanum/DataForge/FileUploader/OralCancer/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "required": [
            "image_id",
            "patient_name",
            "image_path",
            "image_type",
            "image_date",
            "lesion_location",
            "clinical_notes",
            "label"
        ],
        "properties": {
            "image_id": {
                "type": "string"
            },
            "patient_name": {
                "type": "string"
            },
            "image_path": {
                "type": "string"
            },
            "image_type": {
                "type": "string"
            },
            "image_date": {
                "type": "string",
                "format": "date"
            },
            "lesion_location": {
                "type": "string"
            },
            "clinical_notes": {
                "type": "string"
            },
            "label": {
                "type": "string"
            }
        }
    }
}

=== harikrishnanum/DataForge/FileUploader/OralCancer/metadata.json
[
    {
        "image_id": "57da862bb3bc4e0891692b630b1f547e",
        "patient_name": "Greg Larimore",
        "image_path": "images/dataset_280x190_tongue_cancer_facts_ref_guide.jpg",
        "image_type": "jpg",
        "image_date": "2016-08-12",
        "lesion_location": "Roof of the mouth",
        "clinical_notes": "Oral examination reveals a lump or mass in the mouth. Patient reports a burning sensation in the mouth or throat.",
        "label": "Verrucous carcinoma"
    },
    {
        "image_id": "61e1bad31b684b139c4c49f729c39a4e",
        "patient_name": "Louis Finkel",
        "image_path": "images/cancer 6.jpg",
        "image_type": "jpg",
        "image_date": "2013-03-23",
        "lesion_location": "Tongue",
        "clinical_notes": "Oral examination reveals a lesion or ulcer in the mouth. Patient reports a chronic sore throat or hoarseness.",
        "label": "Lymphoma"
    },
    {
        "image_id": "cd133256ae7f48de877683e27a6ea825",
        "patient_name": "Joshua Smith",
        "image_path": "images/dataset_41415_2000_Article_BF4800481_Fig1_HTML.jpg",
        "image_type": "jpg",
        "image_date": "2021-08-16",
        "lesion_location": "Lips",
        "clinical_notes": "Patient reports a lump or swelling in the jaw.",
        "label": "Melanoma"
    },
    {
        "image_id": "b2e04eeaefc14df0aa7e89c5ba506567",
        "patient_name": "Michael Strebe",
        "image_path": "images/dataset_2-1080x675.jpg",
        "image_type": "jpg",
        "image_date": "2022-06-03",
        "lesion_location": "Gums",
        "clinical_notes": "Patient reports a metallic taste in the mouth.",
        "label": "Verrucous carcinoma"
    },
    {
        "image_id": "dfbc19af4ce34f61857c5cb41c843b0c",
        "patient_name": "Gladys Stephenson",
        "image_path": "images/dataset_oral-leukoplakia-br-image-credit-dermnet-new-zealand-br.jpg",
        "image_type": "jpg",
        "image_date": "2023-01-12",
        "lesion_location": "Lips",
        "clinical_notes": "Patient reports a change in the way the teeth fit together. Oral examination reveals a lesion or ulcer in the mouth.",
        "label": "Lymphoma"
    },
    {
        "image_id": "5f16941fa50e4277982048bd20edfc5b",
        "patient_name": "Rhonda Gregg",
        "image_path": "images/skin-cancer-of-the-lip.jpg",
        "image_type": "jpg",
        "image_date": "2014-12-16",
        "lesion_location": "Gums",
        "clinical_notes": "Patient reports a burning sensation in the mouth or throat.",
        "label": "Adenoid cystic carcinoma"
    },
    {
        "image_id": "bf12ba109cfb475f87de34fc8e60e711",
        "patient_name": "Martin Hruby",
        "image_path": "images/SRMJResDentSci_2013_4_1_35_116830_u1.jpg",
        "image_type": "jpg",
        "image_date": "2014-10-15",
        "lesion_location": "Roof of the mouth",
        "clinical_notes": "Patient reports a lump or swelling in the jaw. Patient reports a change in the fit of dentures.",
        "label": "Adenoid cystic carcinoma"
    },
    {
        "image_id": "1b126b5a824241d699e8fc14da6d567d",
        "patient_name": "Jennifer Rose",
        "image_path": "images/oral-leukoplakia-br-image-credit-dermnet-new-zealand-br.jpg",
        "image_type": "jpg",
        "image_date": "2022-07-06",
        "lesion_location": "Roof of the mouth",
        "clinical_notes": "Patient presents with a persistent bad breath.",
        "label": "Verrucous carcinoma"
    },
    {
        "image_id": "94336cf97052465aa7e548965d59f800",
        "patient_name": "Lorraine Rogers",
        "image_path": "images/Oral-Cancer-Screenings.jpg",
        "image_type": "jpg",
        "image_date": "2016-04-11",
        "lesion_location": "Inner lining of the cheeks",
        "clinical_notes": "Patient reports a lump or swelling in the jaw. Oral examination reveals a growth or swelling in the mouth.",
        "label": "Adenoid cystic carcinoma"
    },
    {
        "image_id": "ae787c37841c433bba4aa4c58182f1a9",
        "patient_name": "Christine Leatherwood",
        "image_path": "images/41415_2000_Article_BF4800481_Fig1_HTML.jpg",
        "image_type": "jpg",
        "image_date": "2020-09-22",
        "lesion_location": "Floor of the mouth",
        "clinical_notes": "Patient reports bleeding or pain in the mouth.",
        "label": "Lymphoma"
    },
    {
        "image_id": "f5d2eac6fc7847bcbff8144b68141fa0",
        "patient_name": "Debra Fujioka",
        "image_path": "images/18b79305-949e-4ed8-849c-ec5d5a794752.jpg",
        "image_type": "jpg",
        "image_date": "2017-12-28",
        "lesion_location": "Gums",
        "clinical_notes": "Oral examination reveals a lesion or ulcer in the mouth.",
        "label": "Lymphoma"
    },
    {
        "image_id": "ad178e5b323f44bfa53d8596a64732a4",
        "patient_name": "Patti Johnson",
        "image_path": "images/lip-cancer-pictures-youtube-regarding-lip-cancer-pictures.jpg",
        "image_type": "jpg",
        "image_date": "2021-04-05",
        "lesion_location": "Roof of the mouth",
        "clinical_notes": "Oral examination reveals a lesion or ulcer in the mouth. Patient reports a metallic taste in the mouth. Patient reports difficulty opening the mouth.",
        "label": "Melanoma"
    },
    {
        "image_id": "cc50c2b01c7248b581837ca54dbe51d8",
        "patient_name": "Janet Cleary",
        "image_path": "images/dataset_cancer 6.jpg",
        "image_type": "jpg",
        "image_date": "2015-07-28",
        "lesion_location": "Lips",
        "clinical_notes": "Patient reports a lump or swelling in the jaw.",
        "label": "Adenoid cystic carcinoma"
    },
    {
        "image_id": "b69b986027c84d81b7e0c35eb78a54eb",
        "patient_name": "Thomas White",
        "image_path": "images/Carcinomaoftherighttongue_OCT-20161108085557163.jpg",
        "image_type": "jpg",
        "image_date": "2021-06-21",
        "lesion_location": "Gums",
        "clinical_notes": "Patient presents with a lump or thickening in the cheek or neck. Patient presents with a non-healing ulcer in the mouth.",
        "label": "Verrucous carcinoma"
    },
    {
        "image_id": "b667171508884e1184cf7cd7ebb05ae1",
        "patient_name": "Jessica Mccrary",
        "image_path": "images/dataset_41457tn.jpg",
        "image_type": "jpg",
        "image_date": "2018-07-25",
        "lesion_location": "Roof of the mouth",
        "clinical_notes": "Patient reports a change in the way the teeth fit together.",
        "label": "Squamous cell carcinoma"
    },
    {
        "image_id": "0503735e4ee1461eaf34df42a2b35459",
        "patient_name": "Raymond Lopez",
        "image_path": "images/46e21e7be60567c4b9b2ca9018587f88_XL.jpg",
        "image_type": "jpg",
        "image_date": "2020-07-12",
        "lesion_location": "Roof of the mouth",
        "clinical_notes": "Patient presents with a lump or thickening in the cheek or neck.",
        "label": "Lymphoma"
    },
    {
        "image_id": "73c995fd510c48219c1b98e88dde3668",
        "patient_name": "Sandra Ochoa",
        "image_path": "images/lipreconstruction1.jpg",
        "image_type": "jpg",
        "image_date": "2022-03-25",
        "lesion_location": "Inner lining of the cheeks",
        "clinical_notes": "Patient reports difficulty opening the mouth. Patient presents with a lump or sore in the mouth that does not heal.",
        "label": "Acinic cell carcinoma"
    },
    {
        "image_id": "e2f24601ca3b48e4b1d1197a15164318",
        "patient_name": "Allison Beck",
        "image_path": "images/dataset_1200px-ZungenCa2a (1).jpg",
        "image_type": "jpg",
        "image_date": "2022-04-24",
        "lesion_location": "Floor of the mouth",
        "clinical_notes": "Patient reports difficulty moving the tongue or jaw. Patient reports a persistent cough or sore throat. Patient reports unexplained weight loss and fatigue.",
        "label": "Acinic cell carcinoma"
    },
    {
        "image_id": "c8524b23fa4f4efdb3e03736905d3b31",
        "patient_name": "Laurie Blair",
        "image_path": "images/dataset_squamous-cell-carinoma-of-the-tongue.jpg",
        "image_type": "jpg",
        "image_date": "2020-05-04",
        "lesion_location": "Roof of the mouth",
        "clinical_notes": "Oral examination reveals a growth or swelling in the mouth.",
        "label": "Verrucous carcinoma"
    },
    {
        "image_id": "bb6e91afa7cc4dad8ed97970f2db81a5",
        "patient_name": "Michael Mckillop",
        "image_path": "images/dataset_650x350_oral_cancer_ref_guide.jpg",
        "image_type": "jpg",
        "image_date": "2019-07-05",
        "lesion_location": "Inner lining of the cheeks",
        "clinical_notes": "Patient reports a chronic sore throat or hoarseness.",
        "label": "Acinic cell carcinoma"
    },
    {
        "image_id": "f70cb258b81e474ba4b1199df5574ccb",
        "patient_name": "Pamela Ostroski",
        "image_path": "images/pract_oral_cancer.jpg",
        "image_type": "jpg",
        "image_date": "2010-10-19",
        "lesion_location": "Inner lining of the cheeks",
        "clinical_notes": "Patient reports a feeling of something caught in the throat. Patient reports bleeding or pain in the mouth.",
        "label": "Minor salivary gland carcinomas"
    },
    {
        "image_id": "7473d55d2aaa460693df15d2ebb0dad1",
        "patient_name": "Rebecca Causey",
        "image_path": "images/oral-cancer-by-j-shah-33-728.jpg",
        "image_type": "jpg",
        "image_date": "2012-12-07",
        "lesion_location": "Tongue",
        "clinical_notes": "Patient presents with a lump or thickening in the cheek or neck. Oral examination reveals white or red patches on the gums, tongue, or lining of the mouth.",
        "label": "Verrucous carcinoma"
    },
    {
        "image_id": "a3c8128c5046495c93d1d34465d13447",
        "patient_name": "Mary Remmele",
        "image_path": "images/dataset_1200px-ZungenCa2a.jpg",
        "image_type": "jpg",
